version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-auth-template
    container_name: laravel_auth_template
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bank
      - DB_USERNAME=root
      - DB_PASSWORD=

  db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bank
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: