version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-auth-template
    container_name: laravel_auth_template
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: false
      DB_CONNECTION: ${DB_CONNECTION}

volumes:
  db_data:
